name       : python-executing
version    : 1.2.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/e/executing/executing-1.2.0.tar.gz : 19da64c18d2d851112f09c287f8d3dbbdf725ab0e569077efb6cdcbd3497c107
homepage   : https://github.com/alexmojaki/executing
license    : MIT
component  : programming.python
summary    : Get the currently executing AST node of a frame, and other information
description: |
    This mini-package lets you get information about what a frame is currently doing, particularly the AST node being executed.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
